import React from "react";
import { X, Printer } from "lucide-react";
import ReportHighlights from "./report/ReportHighlights";
import ReportFinancials from "./report/ReportFinancials";

export default function ReportModal({ isOpen, onClose, stats = {}, scenePreset = "commercial" }) {
  if (!isOpen) return null;

  const area = stats.totalRooftopArea || 820.0;
  const panels = stats.panelsCount || 180;
  const kw = stats.systemCapacityKwp || (panels * 0.4).toFixed(1);
  const annualKwh = stats.annualGenerationKwh || Math.round(area * 1850 * 0.20 * 0.82);
  const annualSavings = stats.annualSavingsUsd || Math.round(annualKwh * 0.16);
  const grossCapex = Math.round(kw * 1000 * 2.80);
  const netCapex = Math.round(grossCapex * 0.70);
  const payback = (netCapex / annualSavings).toFixed(1);
  const co2 = stats.co2OffsetTons || ((annualKwh * 0.85) / 2204.62).toFixed(1);

  return (
    <div style={{
      position: "fixed", inset: 0, zIndex: 1000, background: "rgba(0, 0, 0, 0.85)",
      backdropFilter: "blur(12px)", display: "flex", alignItems: "center", justifyContent: "center", padding: "20px"
    }}>
      <div style={{
        background: "#0c111d", border: "1px solid rgba(255, 255, 255, 0.18)",
        borderRadius: "28px", width: "100%", maxWidth: "760px", padding: "32px",
        color: "#ffffff", position: "relative", maxHeight: "90vh", overflowY: "auto", fontFamily: "monospace"
      }}>
        <button
          onClick={onClose}
          style={{ position: "absolute", top: "24px", right: "24px", background: "rgba(255, 255, 255, 0.05)", border: "1px solid rgba(255, 255, 255, 0.1)", color: "#ffffff", padding: "8px", borderRadius: "10px", cursor: "pointer" }}
        >
          <X size={16} />
        </button>

        <div style={{ borderBottom: "1px solid rgba(255, 255, 255, 0.1)", paddingBottom: "20px", marginBottom: "24px" }}>
          <span style={{ fontSize: "0.72rem", color: "#f59e0b", letterSpacing: "0.1em", textTransform: "uppercase", fontWeight: 700 }}>
            CITYGML LOD2 SOLAR FEASIBILITY AUDIT
          </span>
          <h2 style={{ fontSize: "1.6rem", fontWeight: 800, margin: "4px 0 0 0", fontFamily: "sans-serif" }}>
            {stats.name || "Engineering & Financial Simulation Report"}
          </h2>
          <span style={{ fontSize: "0.75rem", color: "#64748b" }}>
            {stats.location ? stats.location : `CAD Geometry: ${scenePreset.toUpperCase()}`} • Generated by SunMap 3D
          </span>
        </div>

        <ReportHighlights kw={kw} panels={panels} annualKwh={annualKwh} stats={stats} />
        <ReportFinancials netCapex={netCapex} annualSavings={annualSavings} payback={payback} co2={co2} />

        <button
          onClick={() => window.print()}
          style={{
            display: "flex", alignItems: "center", justifyContent: "center", gap: "8px",
            width: "100%", background: "#f59e0b", color: "#000000", border: "none",
            padding: "14px", borderRadius: "14px", fontWeight: 800, cursor: "pointer"
          }}
        >
          <Printer size={16} /> Print Bankable Engineering Dossier
        </button>
      </div>
    </div>
  );
}
